// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace implementation.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001093820_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("implementation.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecisaoFinal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncidentesCredito")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Motivos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Prazo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrestacaoNova")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrestacoesAtuais")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RendimentoMensal")
                        .HasColumnType("TEXT");

                    b.Property<string>("SituacaoProfissional")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxaEsforco")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorPretendido")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
